### ISSUE TITLE
下一阶段主要工作

### ISSUE THREAD

**Issue by VictorHuu** [DesignPatternGr/NewEnergyCarAssembly#4]
**TODO:**
**CI/CD相关：**

- [ ]  使用Google Test框架测试10个库
- [ ]  采用只能输入的方式对可执行文件的输入响应

**答辩相关：**
- [ ]  再增加5个设计模式,这5个人的2个设计模式中需要有至少1个设计地非常精妙
- [ ]  1个人制作PPT
- [ ]  1个人负责答辩
- [ ]  我负责CI/CD
- [ ]  2个人负责故事润色

**个人相关：**
- [ ]  类图与简要文档 @DesignPatternGr/team
